# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ups_amazon.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ups_amazon.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n\x10ups_amazon.proto\"\x1d\n\nUA_Connect\x12\x0f\n\x07worldid\x18\x01 \x02(\x03\"\x90\x01\n\x0cUA_TruckCall\x12\x12\n\npackage_id\x18\x01 \x02(\x03\x12\x1b\n\x08products\x18\x02 \x03(\x0b\x32\t.AProduct\x12\r\n\x05whnum\x18\x03 \x02(\x05\x12\x10\n\x08owner_id\x18\x04 \x02(\x03\x12\x0e\n\x06\x64\x65st_x\x18\x05 \x02(\x05\x12\x0e\n\x06\x64\x65st_y\x18\x06 \x02(\x05\x12\x0e\n\x06seqnum\x18\x07 \x02(\x03\"X\n\x0cUA_GoDeliver\x12\x0f\n\x07truckid\x18\x01 \x02(\x05\x12\x11\n\tpackageid\x18\x02 \x02(\x03\x12\t\n\x01x\x18\x03 \x02(\x05\x12\t\n\x01y\x18\x04 \x02(\x05\x12\x0e\n\x06seqnum\x18\x05 \x02(\x03\"B\n\x0fUA_TruckArrived\x12\r\n\x05whnum\x18\x01 \x02(\x05\x12\x10\n\x08truck_id\x18\x02 \x02(\x05\x12\x0e\n\x06seqnum\x18\x03 \x02(\x03\"B\n\x0cUA_Delivered\x12\x11\n\tpackageid\x18\x01 \x02(\x03\x12\x0f\n\x07truckid\x18\x02 \x02(\x05\x12\x0e\n\x06seqnum\x18\x03 \x02(\x03\"_\n\x0bUA_Commands\x12 \n\ttruckCall\x18\x01 \x03(\x0b\x32\r.UA_TruckCall\x12 \n\tgoDeliver\x18\x02 \x03(\x0b\x32\r.UA_GoDeliver\x12\x0c\n\x04\x61\x63ks\x18\x03 \x03(\x03\"f\n\x0cUA_Responses\x12&\n\x0ctruckArrived\x18\x01 \x03(\x0b\x32\x10.UA_TruckArrived\x12 \n\tdelivered\x18\x02 \x03(\x0b\x32\r.UA_Delivered\x12\x0c\n\x04\x61\x63ks\x18\x03 \x03(\x03\":\n\x08\x41Product\x12\n\n\x02id\x18\x01 \x02(\x03\x12\x13\n\x0b\x64\x65scription\x18\x02 \x02(\t\x12\r\n\x05\x63ount\x18\x03 \x02(\x05'
)




_UA_CONNECT = _descriptor.Descriptor(
  name='UA_Connect',
  full_name='UA_Connect',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='worldid', full_name='UA_Connect.worldid', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=49,
)


_UA_TRUCKCALL = _descriptor.Descriptor(
  name='UA_TruckCall',
  full_name='UA_TruckCall',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='package_id', full_name='UA_TruckCall.package_id', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='products', full_name='UA_TruckCall.products', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='whnum', full_name='UA_TruckCall.whnum', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='owner_id', full_name='UA_TruckCall.owner_id', index=3,
      number=4, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dest_x', full_name='UA_TruckCall.dest_x', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dest_y', full_name='UA_TruckCall.dest_y', index=5,
      number=6, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='seqnum', full_name='UA_TruckCall.seqnum', index=6,
      number=7, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=196,
)


_UA_GODELIVER = _descriptor.Descriptor(
  name='UA_GoDeliver',
  full_name='UA_GoDeliver',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='truckid', full_name='UA_GoDeliver.truckid', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='packageid', full_name='UA_GoDeliver.packageid', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='x', full_name='UA_GoDeliver.x', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='UA_GoDeliver.y', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='seqnum', full_name='UA_GoDeliver.seqnum', index=4,
      number=5, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=198,
  serialized_end=286,
)


_UA_TRUCKARRIVED = _descriptor.Descriptor(
  name='UA_TruckArrived',
  full_name='UA_TruckArrived',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='whnum', full_name='UA_TruckArrived.whnum', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='truck_id', full_name='UA_TruckArrived.truck_id', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='seqnum', full_name='UA_TruckArrived.seqnum', index=2,
      number=3, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=288,
  serialized_end=354,
)


_UA_DELIVERED = _descriptor.Descriptor(
  name='UA_Delivered',
  full_name='UA_Delivered',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='packageid', full_name='UA_Delivered.packageid', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='truckid', full_name='UA_Delivered.truckid', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='seqnum', full_name='UA_Delivered.seqnum', index=2,
      number=3, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=356,
  serialized_end=422,
)


_UA_COMMANDS = _descriptor.Descriptor(
  name='UA_Commands',
  full_name='UA_Commands',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='truckCall', full_name='UA_Commands.truckCall', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='goDeliver', full_name='UA_Commands.goDeliver', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='acks', full_name='UA_Commands.acks', index=2,
      number=3, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=424,
  serialized_end=519,
)


_UA_RESPONSES = _descriptor.Descriptor(
  name='UA_Responses',
  full_name='UA_Responses',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='truckArrived', full_name='UA_Responses.truckArrived', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='delivered', full_name='UA_Responses.delivered', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='acks', full_name='UA_Responses.acks', index=2,
      number=3, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=521,
  serialized_end=623,
)


_APRODUCT = _descriptor.Descriptor(
  name='AProduct',
  full_name='AProduct',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='AProduct.id', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='description', full_name='AProduct.description', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='count', full_name='AProduct.count', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=625,
  serialized_end=683,
)

_UA_TRUCKCALL.fields_by_name['products'].message_type = _APRODUCT
_UA_COMMANDS.fields_by_name['truckCall'].message_type = _UA_TRUCKCALL
_UA_COMMANDS.fields_by_name['goDeliver'].message_type = _UA_GODELIVER
_UA_RESPONSES.fields_by_name['truckArrived'].message_type = _UA_TRUCKARRIVED
_UA_RESPONSES.fields_by_name['delivered'].message_type = _UA_DELIVERED
DESCRIPTOR.message_types_by_name['UA_Connect'] = _UA_CONNECT
DESCRIPTOR.message_types_by_name['UA_TruckCall'] = _UA_TRUCKCALL
DESCRIPTOR.message_types_by_name['UA_GoDeliver'] = _UA_GODELIVER
DESCRIPTOR.message_types_by_name['UA_TruckArrived'] = _UA_TRUCKARRIVED
DESCRIPTOR.message_types_by_name['UA_Delivered'] = _UA_DELIVERED
DESCRIPTOR.message_types_by_name['UA_Commands'] = _UA_COMMANDS
DESCRIPTOR.message_types_by_name['UA_Responses'] = _UA_RESPONSES
DESCRIPTOR.message_types_by_name['AProduct'] = _APRODUCT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UA_Connect = _reflection.GeneratedProtocolMessageType('UA_Connect', (_message.Message,), {
  'DESCRIPTOR' : _UA_CONNECT,
  '__module__' : 'ups_amazon_pb2'
  # @@protoc_insertion_point(class_scope:UA_Connect)
  })
_sym_db.RegisterMessage(UA_Connect)

UA_TruckCall = _reflection.GeneratedProtocolMessageType('UA_TruckCall', (_message.Message,), {
  'DESCRIPTOR' : _UA_TRUCKCALL,
  '__module__' : 'ups_amazon_pb2'
  # @@protoc_insertion_point(class_scope:UA_TruckCall)
  })
_sym_db.RegisterMessage(UA_TruckCall)

UA_GoDeliver = _reflection.GeneratedProtocolMessageType('UA_GoDeliver', (_message.Message,), {
  'DESCRIPTOR' : _UA_GODELIVER,
  '__module__' : 'ups_amazon_pb2'
  # @@protoc_insertion_point(class_scope:UA_GoDeliver)
  })
_sym_db.RegisterMessage(UA_GoDeliver)

UA_TruckArrived = _reflection.GeneratedProtocolMessageType('UA_TruckArrived', (_message.Message,), {
  'DESCRIPTOR' : _UA_TRUCKARRIVED,
  '__module__' : 'ups_amazon_pb2'
  # @@protoc_insertion_point(class_scope:UA_TruckArrived)
  })
_sym_db.RegisterMessage(UA_TruckArrived)

UA_Delivered = _reflection.GeneratedProtocolMessageType('UA_Delivered', (_message.Message,), {
  'DESCRIPTOR' : _UA_DELIVERED,
  '__module__' : 'ups_amazon_pb2'
  # @@protoc_insertion_point(class_scope:UA_Delivered)
  })
_sym_db.RegisterMessage(UA_Delivered)

UA_Commands = _reflection.GeneratedProtocolMessageType('UA_Commands', (_message.Message,), {
  'DESCRIPTOR' : _UA_COMMANDS,
  '__module__' : 'ups_amazon_pb2'
  # @@protoc_insertion_point(class_scope:UA_Commands)
  })
_sym_db.RegisterMessage(UA_Commands)

UA_Responses = _reflection.GeneratedProtocolMessageType('UA_Responses', (_message.Message,), {
  'DESCRIPTOR' : _UA_RESPONSES,
  '__module__' : 'ups_amazon_pb2'
  # @@protoc_insertion_point(class_scope:UA_Responses)
  })
_sym_db.RegisterMessage(UA_Responses)

AProduct = _reflection.GeneratedProtocolMessageType('AProduct', (_message.Message,), {
  'DESCRIPTOR' : _APRODUCT,
  '__module__' : 'ups_amazon_pb2'
  # @@protoc_insertion_point(class_scope:AProduct)
  })
_sym_db.RegisterMessage(AProduct)


# @@protoc_insertion_point(module_scope)
